spring:
  application:
    name: ticket-tracker
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tickettracker5
    username: 'postgres'
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/tickettracker
  web:
    error:
      include-message: always